### ISSUE TITLE
scarabizor.py test fails due to missing `PARAMS.out`

### ISSUE THREAD

**Issue by pwintz** [pwintz/sharc#5]
On commit 9866b98ee386965ca, running test_scarabizor.py after building SHARC from a clean repo fails because `PARAMS.out` is expected to be in the test folder, but it was not included in the Git commit.
```
2. Running Tests...
.................................
.
..E..................................
======================================================================
ERROR: test_read_params_file (test_scarabizor.TestScarabPARAMSReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dcuser/resources/tests/test_scarabizor.py", line 55, in test_read_params_file
    params_lines = scarab_params_reader.read_params_file(TESTS_FOLDER + '/PARAMS.out')
  File "/home/dcuser/resources/sharc/scarabizor.py", line 170, in read_params_file
    return ParamsData.from_file(filename).get_lines()
  File "/home/dcuser/resources/sharc/scarabizor.py", line 79, in from_file
    assertFileExists(filename)
  File "/home/dcuser/resources/sharc/utils.py", line 40, in assertFileExists
    raise IOError(err_msg)
OSError: Expected /home/dcuser/resources/tests/PARAMS.out to exist but it does not.

----------------------------------------------------------------------
```

**Comment by pwintz** [comment]
Fixed in https://github.com/pwintz/sharc/commit/abe99f0f0f32714929aa3c865fd3b0984c3f396d.
